# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youapp', '0007_auto_20170423_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='wall',
            new_name='user',
        ),
    ]
