# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('youapp', '0009_movie_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255, verbose_name='thumbnail_url'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=embed_video.fields.EmbedVideoField(verbose_name='Ссылка'),
        ),
    ]
