# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youapp', '0012_auto_20170426_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='user',
            name='purchased',
            field=models.ManyToManyField(blank=True, to='youapp.Movie', verbose_name='Купленные видео'),
        ),
    ]
